# Generated by Django 6.0.7 on 2026-07-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0002_userprofile_can_add_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='referred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='queue_manager.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.CharField(help_text='Patient ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled/Skipped'), ('TRANSFERRED', 'Transferred')], default='WAITING', max_length=20),
        ),
    ]
