# Generated by Django 6.0.7 on 2026-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0003_patient_referred_from_alter_patient_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_token',
            field=models.PositiveIntegerField(default=1, help_text='First token number for this room each day. Tokens continue from here or from the last issued number.'),
        ),
    ]
