# Generated by Django 6.0.7 on 2026-07-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0004_room_start_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rooms', models.ManyToManyField(blank=True, related_name='groups', to='queue_manager.room')),
            ],
        ),
    ]
