# Generated by Django 6.0.7 on 2026-07-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0006_department_registerissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerissue',
            name='patient',
        ),
    ]
